[package]
name = "near_fusion"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "3.1.0"
hex = "0.4.3"
sha3 = "0.10.8"

[dev-dependencies]
near-sdk = "3.1.0"
